language: go
go:
  - 1.14

sudo: required

os:
  - linux
  - osx

install:
  - echo "install"
  - go get -u github.com/go-bindata/go-bindata/...

script:
  - echo "script"
  - make dev
  - go test -race -coverprofile=coverage.txt -covermode=atomic

before_install:
  - go get -t -v ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)